name: ffmpeg_config_on_fail
on:
  push:
    paths:
      - ffmpeg/**
  pull_request:
    paths:
      - ffmpeg/**
  workflow_dispatch:
jobs:
  macosx-x86_64:
    runs-on: macos-10.15
    strategy:
      matrix:
        ext: [""]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-macosx@actions
      - name: The job has failed
        if: ${{ failure() }}
        run: cat ffmpeg/cppbuild/macosx-x86_64/ffmpeg-4.4/ffbuild/config.log
  windows-x86:
    runs-on: windows-2019
    strategy:
      matrix:
        ext: [""]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
      - name: The job has failed
        if: ${{ failure() }}
        run: cat ffmpeg/cppbuild/windows-x86/ffmpeg-4.4/ffbuild/config.log
  windows-x86_64:
    runs-on: windows-2019
    strategy:
      matrix:
        ext: [""]
    steps:
      - uses: bytedeco/javacpp-presets/.github/actions/deploy-windows@actions
      - name: The job has failed
        if: ${{ failure() }}
        run: cat ffmpeg/cppbuild/windows-x86_64/ffmpeg-4.4/ffbuild/config.log
